use QuanLy_Kho
go

CREATE PROC uspAddProduct
	@BARCODE nvarchar(13),
	@TENHH nvarchar(50),
	@TENTAT nvarchar(50), 
	@DVT nvarchar(50), 
	@DONGIA decimal(18,0), 
	@MANCC int, 
	@MAXX int, 
	@IDNHOM nvarchar(50), 
	@MOTA nvarchar(500), 
	@CREATED_DATE datetime, 
	@CREATED_BY int, 
	@DISABLED bit,
	@pImage image = NULL

AS
BEGIN
    INSERT INTO tb_HANGHOA (
        BARCODE, TENHH, TENTAT, DVT, DONGIA, MANCC, MAXX, IDNHOM, MOTA,
        CREATED_DATE, CREATED_BY, DISABLED, pImage
    )
    VALUES (
        @BARCODE, @TENHH, @TENTAT, @DVT, @DONGIA, @MANCC, @MAXX, @IDNHOM, @MOTA,
        @CREATED_DATE, @CREATED_BY, @DISABLED, @pImage
    )
END
GO

CREATE PROC uspUpdateProduct
	@BARCODE nvarchar(13),
	@TENHH nvarchar(50),
	@TENTAT nvarchar(50), 
	@DVT nvarchar(50), 
	@DONGIA decimal(18,0), 
	@MANCC int, 
	@MAXX int, 
	@IDNHOM nvarchar(50), 
	@MOTA nvarchar(500), 
	@CREATED_DATE datetime, 
	@CREATED_BY int, 
	@DISABLED bit,
	@pImage image = null
AS
BEGIN
    UPDATE tb_HANGHOA
	SET TENHH = @TENHH,
		TENTAT = @TENTAT,
		DVT = @DVT,
		DONGIA = @DONGIA,
		MANCC = @MANCC,
		MAXX = @MAXX,
		IDNHOM = @IDNHOM,
		MOTA = @MOTA,
		CREATED_DATE = @CREATED_DATE,
		CREATED_BY = @CREATED_BY,
		DISABLED = @DISABLED,
		pImage = @pImage
	WHERE BARCODE = @BARCODE
END
GO

CREATE PROC uspDeleteProduct
	@BARCODE nvarchar(13)

AS
BEGIN
    DELETE FROM tb_HANGHOA WHERE BARCODE = @BARCODE
END
GO


CREATE PROC uspAddSupplier
    @TENNCC NVARCHAR(50),
    @EMAIL NVARCHAR(50) = NULL,
    @DIENTHOAI NVARCHAR(50) = NULL,
    @FAX NVARCHAR(50) = NULL,
    @DIACHI NVARCHAR(200) = NULL,
    @CREATED_DATE DATETIME,
    @DISABLED BIT
AS
BEGIN
    INSERT INTO tb_NHACUNGCAP (
        TENNCC, EMAIL, DIENTHOAI, FAX, DIACHI, CREATED_DATE, DISABLED
    )
    VALUES (
        @TENNCC, @EMAIL, @DIENTHOAI, @FAX, @DIACHI, @CREATED_DATE, @DISABLED
    )
END
GO

CREATE PROC uspUpdateSupplier
    @MANCC INT,
    @TENNCC NVARCHAR(50),
    @EMAIL NVARCHAR(50) = NULL,
    @DIENTHOAI NVARCHAR(50) = NULL,
    @FAX NVARCHAR(50) = NULL,
    @DIACHI NVARCHAR(200) = NULL,
    @CREATED_DATE DATETIME,
    @DISABLED BIT
AS
BEGIN
    UPDATE tb_NHACUNGCAP
    SET TENNCC = @TENNCC,
        EMAIL = @EMAIL,
        DIENTHOAI = @DIENTHOAI,
        FAX = @FAX,
        DIACHI = @DIACHI,
        CREATED_DATE = @CREATED_DATE,
        DISABLED = @DISABLED
    WHERE MANCC = @MANCC
END
GO

CREATE PROC uspDeleteSupplier
    @MANCC INT
AS
BEGIN
    DELETE FROM tb_NHACUNGCAP WHERE MANCC = @MANCC
END
GO
